--- # starting & installin
- hosts: all
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: installing httpd
      yum:
        name: httpd
        service: present
      when: ansible_os_family == "RedHat"
     
    - name: starting httpd service
      action: name=httpd service=started
      when: ansible_os_family == "RedHat"

    - name: installing apache2 s/w
      apt:
       name: apache2
       state: present
      when: ansible_os_family == "Debian"

    - name: starting apache2 s/w
      service:
       name: apache2
       state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: rahul
        mode: 0666




