--- # creating directory
- hosts: all
  connection: ssh
  user: ansible
  name: my test playbook
  become: yes
    
  tasks:
    - name: copying a file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: chetan
