--- # creating user
- hosts: all
  become: yes
  connection: ssh
  user: ansible

  tasks:
    - name: creating multiple users
      user: name='{{item}}' state=present
      with_items:
       - raj
       - shiv
       - mohammad
       - jesus  
