--- #
- name: hosts
  become: yes
  hosts: all

  tasks:
    - name: installing pkg
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        service: started      
